##############################################################
# Mobile Application Programming (SCSJ3623)
# Semester 2, 2019/2020
##############################################################

# REST API Server on Local Firebase
# @baseUrl = http://localhost:5001/helmi-backend-firebase-rest/us-central1/api

# REST API Server on Live Firebase
@baseUrl = https://us-central1-catcare-81b0d.cloudfunctions.net/api

### Getting the list of quote
GET {{baseUrl}}/users

###  Getting a quote of given id
GET {{baseUrl}}/users/KhpuUfQVcLIfKrG1PaJT

###  Create a new quote
POST {{baseUrl}}/users/jasm
Content-Type: application/json

### Update the status of a given quote (whether is completed or not)
PATCH {{baseUrl}}/KhpuUfQVcLIfKrG1PaJT
Content-Type: application/json

{
    "name": "Abu"
}


### Replace the entire fields of a given quote
PUT {{baseUrl}}/users/KhpuUfQVcLIfKrG1PaJT
Content-Type: application/json

{
    "location":"South Africa",
    "name":"Abul",
    "phone":"+2018290"
}

### Deleting a given quote
DELETE {{baseUrl}}/users/YB28uLhni6it2Sr3RsHc